{{- if (and (eq .Values.database.type "internal") (not .Values.database.internal.secretName)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.database" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
{{- end -}}
